# Generated by Django 4.2.19 on 2025-02-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_studenttoken_alter_student_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
