# Generated by Django 4.2.19 on 2025-02-26 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0004_alter_student_groups_alter_student_user_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={},
        ),
        migrations.AlterModelManagers(
            name="student",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="student",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="student",
            name="username",
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="StudentToken",
        ),
    ]
