# Generated by Django 4.2.19 on 2025-02-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.FileField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
