# Generated by Django 4.2.19 on 2025-03-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_savedpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "Notes"),
                    (2, "Events"),
                    (3, "Announcements"),
                    (5, "Assignments"),
                    (9, "Technology"),
                    (6, "Projects"),
                    (7, "Lectures"),
                    (8, "Lost Things"),
                ]
            ),
        ),
    ]
